### PR TITLE
storage: fix UB taking pointer to inner type T

### PR DESCRIPTION
**Pull request by johannst**
Casting the pointer `Storage<T>::value_` to `T` is undefined according to the standard [basic.life/8], as it violates item (8.2), since the types are not equal [1].

Therefore, we need to launder the pointer after reinterpreting it.

See also the examples in std::launder[2] and std::aligned_storage [3].

Not sure I follow your style correctly, please let me know.

Best

[1] https://timsong-cpp.github.io/cppwp/n4868/basic.life#8
[2] https://en.cppreference.com/w/cpp/utility/launder
[3] https://en.cppreference.com/w/cpp/types/aligned_storage
[4] https://timsong-cpp.github.io/cppwp/n4868/ptr.launder

### CODE REVIEW

**Comment by TheNumbat** [comment]
Good timing, I was just thinking I should add a std::launder equivalent. I'll also add the launder in Variant.
Style looks fine (though I'm not sure how the existing code ended up using `protected`...)

**Comment by TheNumbat** [comment]
Oh, it seems MSVC doesn't expose `__is_function`. Will also fix that.

**Comment by johannst** [comment]
Forgot the poor variant again, out of sight out of mind I guess :^)

> Style looks fine (though I'm not sure how the existing code ended up using protected...)

In the `Storage` class? If by accident, then we can also marl it `private`.

> Oh, it seems MSVC doesn't expose __is_function. Will also fix that.

Oops, didn't have a machine at hand. Probably should have checked before. Thanks for fixing.

**Comment by TheNumbat** [comment]
Yeah, I just got rid of the `protected`.
Normally the CI build would catch errors from MSVC, but the GitHub runners don't have the latest compiler version yet.

**Comment by johannst** [comment]
A small note, `__is_void()` also checks for `cv` qualified `void`, whereas the new `Is_Void` trait does not.

**Comment by TheNumbat** [comment]
Ah, good point

**Pull request merged**
